"""Dictionary Migration

Revision ID: 086afd4fedfa
Revises: 411e18790cb1
Create Date: 2022-06-01 16:20:02.208511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086afd4fedfa'
down_revision = '411e18790cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('dictionary', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'dictionary')
    # ### end Alembic commands ###
